// ui/src/components/Visualizer.tsx
import React, { useState, useRef, useEffect, useCallback } from 'react';
import Machine from './Machine';
import MachineLink from './MachineLink';
import { Machine as MachineType, Link } from '../types';
import './Visualizer.css';

interface VisualizerProps {
    machines: MachineType[];
    links: Link[];
    onMachineClick: (machine: MachineType) => void;
    isReduced: boolean;
    initialPositions?: Record<string, Position>;
    onPositionsChange?: (positions: Record<string, Position>) => void;
}

interface Position {
    x: number;
    y: number;
}

const Visualizer: React.FC<VisualizerProps> = ({ 
    machines, 
    links, 
    onMachineClick,
    isReduced,
    initialPositions,
    onPositionsChange
}) => {
    const svgRef = useRef<SVGSVGElement>(null);
    const [positions, setPositions] = useState<Record<string, Position>>({});
    const [previousPositions, setPreviousPositions] = useState<Record<string, Position>>({});
    const [dragging, setDragging] = useState<string | null>(null);
    const [viewBox, setViewBox] = useState({ x: 0, y: 0, width: 550, height: 350 });
    const [isPanning, setIsPanning] = useState(false);
    const [lastPosition, setLastPosition] = useState({ x: 0, y: 0 });
    const [scale, setScale] = useState(1);
    const [activeLinks, setActiveLinks] = useState<string[]>([]);
    const [highlightedMachine, setHighlightedMachine] = useState<string | null>(null);
    const [animationInProgress, setAnimationInProgress] = useState(false);
    
    const calculateCirclePositions = useCallback(() => {
        const centerX = 275;
        const centerY = 175;
        const radius = 100;
        
        const circlePositions: Record<string, Position> = {};
        machines.forEach((machine, index) => {
            const angle = (index * 2 * Math.PI) / machines.length;
            circlePositions[machine.id] = {
                x: centerX + radius * Math.cos(angle),
                y: centerY + radius * Math.sin(angle)
            };
        });
        
        return circlePositions;
    }, [machines]);
    
    useEffect(() => {
        if (initialPositions && Object.keys(initialPositions).length > 0) {
            setPositions(initialPositions);
        } else {
            const freshCirclePositions = calculateCirclePositions();
            setPositions(freshCirclePositions);
        }
    }, [initialPositions, calculateCirclePositions]);
    
    useEffect(() => {
        const freshCirclePositions = calculateCirclePositions();
        setPreviousPositions({...positions});
        
        setPositions(prev => {
            const updatedPositions = { ...prev };
            machines.forEach(machine => {
                if (!updatedPositions[machine.id]) {
                    updatedPositions[machine.id] = freshCirclePositions[machine.id];
                }
            });
            
            return updatedPositions;
        });
        
        if (machines.some(machine => !positions[machine.id])) {
            setAnimationInProgress(true);
            setTimeout(() => setAnimationInProgress(false), 800);
        }
    }, [machines, calculateCirclePositions, positions]);
    
    const handleSvgMouseDown = (e: React.MouseEvent) => {
        if (e.button === 0 && !dragging) {
            setIsPanning(true);
            setLastPosition({ x: e.clientX, y: e.clientY });
        }
    };
    
    const handleSvgMouseMove = (e: React.MouseEvent) => {
        if (dragging) {
            const svg = svgRef.current;
            if (!svg) return;
            
            const point = svg.createSVGPoint();
            point.x = e.clientX;
            point.y = e.clientY;
            
            const svgP = point.matrixTransform(svg.getScreenCTM()?.inverse());
            
            const newPositions = {
                ...positions,
                [dragging]: {
                    x: svgP.x,
                    y: svgP.y
                }
            };
            
            setPositions(newPositions);
            
            if (onPositionsChange) {
                onPositionsChange(newPositions);
            }
            
            const connectedLinks = links
                .filter(link => link.source === dragging || link.target === dragging)
                .map(link => `${link.source}-${link.target}`);
            
            setActiveLinks(connectedLinks);
        } else if (isPanning) {
            const dx = e.clientX - lastPosition.x;
            const dy = e.clientY - lastPosition.y;
            
            const panSpeed = 1 / scale;
            
            setViewBox(prev => ({
                ...prev,
                x: prev.x - dx * panSpeed,
                y: prev.y - dy * panSpeed
            }));
            
            setLastPosition({ x: e.clientX, y: e.clientY });
        }
    };
    
    const handleSvgMouseUp = () => {
        setIsPanning(false);
        if (dragging) {
            setAnimationInProgress(true);
            setTimeout(() => {
                setAnimationInProgress(false);
                setActiveLinks([]);
            }, 300);
        }
        setDragging(null);
    };
    
    const handleSvgMouseLeave = () => {
        setIsPanning(false);
        setDragging(null);
        setActiveLinks([]);
    };
    
    const handleMachineDragStart = (id: string, e: React.MouseEvent) => {
        e.stopPropagation();
        setDragging(id);
        
        const connectedLinks = links
            .filter(link => link.source === id || link.target === id)
            .map(link => `${link.source}-${link.target}`);
        
        setActiveLinks(connectedLinks);
    };
    
    const handleMachineHover = (id: string) => {
        if (!dragging) {
            setHighlightedMachine(id);
            
            const connectedLinks = links
                .filter(link => link.source === id || link.target === id)
                .map(link => `${link.source}-${link.target}`);
            
            setActiveLinks(connectedLinks);
        }
    };
    
    const handleMachineLeave = () => {
        if (!dragging) {
            setHighlightedMachine(null);
            setActiveLinks([]);
        }
    };
    
    const handleWheel = (e: React.WheelEvent) => {
        e.preventDefault();
        
        const svg = svgRef.current;
        if (!svg) return;
        
        const point = svg.createSVGPoint();
        point.x = e.clientX;
        point.y = e.clientY;
        const svgP = point.matrixTransform(svg.getScreenCTM()?.inverse());
        
        const zoomFactor = e.deltaY > 0 ? 1.1 : 0.9;
        const newScale = Math.max(0.5, Math.min(5, scale * zoomFactor));
        
        const newWidth = viewBox.width * (scale / newScale);
        const newHeight = viewBox.height * (scale / newScale);
        
        const mouseXRatio = (svgP.x - viewBox.x) / viewBox.width;
        const mouseYRatio = (svgP.y - viewBox.y) / viewBox.height;
        
        const newX = svgP.x - mouseXRatio * newWidth;
        const newY = svgP.y - mouseYRatio * newHeight;
        
        setViewBox({
            x: newX,
            y: newY,
            width: newWidth,
            height: newHeight
        });
        
        setScale(newScale);
    };
    
    const handleZoomIn = () => {
        setAnimationInProgress(true);
        setScale(prev => {
            const newScale = Math.min(5, prev * 1.2);
            setViewBox(prev => {
                const centerX = prev.x + prev.width / 2;
                const centerY = prev.y + prev.height / 2;
                const newWidth = prev.width * (scale / newScale);
                const newHeight = prev.height * (scale / newScale);
                return {
                    x: centerX - newWidth / 2,
                    y: centerY - newHeight / 2,
                    width: newWidth,
                    height: newHeight
                };
            });
            return newScale;
        });
        setTimeout(() => setAnimationInProgress(false), 300);
    };
    
    const handleZoomOut = () => {
        setAnimationInProgress(true);
        setScale(prev => {
            const newScale = Math.max(0.5, prev / 1.2);
            setViewBox(prev => {
                const centerX = prev.x + prev.width / 2;
                const centerY = prev.y + prev.height / 2;
                const newWidth = prev.width * (scale / newScale);
                const newHeight = prev.height * (scale / newScale);
                return {
                    x: centerX - newWidth / 2,
                    y: centerY - newHeight / 2,
                    width: newWidth,
                    height: newHeight
                };
            });
            return newScale;
        });
        setTimeout(() => setAnimationInProgress(false), 300);
    };
    
    const handleResetPositions = () => {
        setAnimationInProgress(true);
        setPreviousPositions({...positions});
        
        const freshCirclePositions = calculateCirclePositions();
        setPositions(freshCirclePositions);
        
        if (onPositionsChange) {
            onPositionsChange(freshCirclePositions);
        }
        
        setViewBox({ x: 0, y: 0, width: 550, height: 350 });
        setScale(1);
        
        setTimeout(() => setAnimationInProgress(false), 800);
    };
    
    const [pulseEffect, setPulseEffect] = useState(false);
    useEffect(() => {
        if (animationInProgress) {
            setPulseEffect(true);
            const timer = setTimeout(() => setPulseEffect(false), 800);
            return () => clearTimeout(timer);
        }
    }, [animationInProgress]);
    
    const viewBoxString = `${viewBox.x} ${viewBox.y} ${viewBox.width} ${viewBox.height}`;
    
    const getMachinePosition = (machineId: string) => {
        if (!positions[machineId]) return { x: 0, y: 0 };
        
        if (animationInProgress && previousPositions[machineId]) {
            return {
                x: positions[machineId].x,
                y: positions[machineId].y,
                animate: true,
                fromX: previousPositions[machineId].x,
                fromY: previousPositions[machineId].y
            };
        }
        
        return positions[machineId];
    };
    
    const getLinkId = (source: string, target: string) => `${source}-${target}`;
    
    return (
        <div className={`visualizer ${isReduced ? 'reduced' : ''}`}>
            <svg 
                ref={svgRef}
                width="100%" 
                height="100%" 
                viewBox={viewBoxString}
                onMouseDown={handleSvgMouseDown}
                onMouseMove={handleSvgMouseMove}
                onMouseUp={handleSvgMouseUp}
                onMouseLeave={handleSvgMouseLeave}
                onWheel={handleWheel}
                style={{ transition: animationInProgress ? 'all 0.3s ease' : 'none' }}
            > 
                {/* Connection links */}
                {links.map((link, index) => {
                    // Only render links if we have positions for both machines
                    if (!positions[link.source] || !positions[link.target]) return null;
                    
                    const linkId = getLinkId(link.source, link.target);
                    const isActive = activeLinks.includes(linkId);
                    const sourcePos = getMachinePosition(link.source);
                    const targetPos = getMachinePosition(link.target);
                    
                    return (
                        <g key={index} className={isActive ? 'active-link' : ''}>
                            <MachineLink
                                sourceX={sourcePos.x}
                                sourceY={sourcePos.y}
                                targetX={targetPos.x}
                                targetY={targetPos.y}
                                type={link.type}
                            />
                            {isActive && (
                                <circle
                                    cx={(sourcePos.x + targetPos.x) / 2}
                                    cy={(sourcePos.y + targetPos.y) / 2}
                                    r="3"
                                    fill={link.type === "connected" ? "#00FF9D" : "#FF3333"}
                                    opacity="0.8"
                                >
                                    <animate
                                        attributeName="r"
                                        values="3;5;3"
                                        dur="1.5s"
                                        repeatCount="indefinite"
                                    />
                                </circle>
                            )}
                        </g>
                    );
                })}
                
                {links.filter(link => link.type === "connected").map((link, index) => {
                    if (!positions[link.source] || !positions[link.target]) return null;
                    
                    const sourcePos = positions[link.source];
                    const targetPos = positions[link.target];
                    
                    const angle = Math.atan2(targetPos.y - sourcePos.y, targetPos.x - sourcePos.x);
                    
                    const radius = 30;
                    const startX = sourcePos.x + Math.cos(angle) * radius;
                    const startY = sourcePos.y + Math.sin(angle) * radius;
                    const endX = targetPos.x - Math.cos(angle) * radius;
                    const endY = targetPos.y - Math.sin(angle) * radius;
                    
                    return (
                        <g key={`flow-${index}`}>
                            <circle r="2" fill="#00FF9D">
                                <animateMotion
                                    path={`M${startX},${startY} L${endX},${endY}`}
                                    dur="1.5s"
                                    repeatCount="indefinite"
                                />
                            </circle>
                            <circle r="2" fill="#00FF9D">
                                <animateMotion
                                    path={`M${endX},${endY} L${startX},${startY}`}
                                    dur="1.5s"
                                    repeatCount="indefinite"
                                />
                            </circle>
                        </g>
                    );
                })}
                
                {machines.map(machine => {
                    const machinePos = getMachinePosition(machine.id);
                    if (!machinePos) return null;
                    
                    const isHighlighted = highlightedMachine === machine.id || dragging === machine.id;
                    
                    return (
                        <g 
                            key={machine.id}
                            onMouseDown={(e) => handleMachineDragStart(machine.id, e)}
                            onMouseEnter={() => handleMachineHover(machine.id)}
                            onMouseLeave={handleMachineLeave}
                            style={{ 
                                transition: animationInProgress ? 'transform 0.8s cubic-bezier(0.34, 1.56, 0.64, 1)' : 'none',
                                transform: `translate(${machinePos.x}px, ${machinePos.y}px)`,
                                transformOrigin: '0 0'
                            }}
                        >
                            {isHighlighted && (
                                <circle
                                    cx="0"
                                    cy="0"
                                    r="35"
                                    fill="transparent"
                                    stroke={machine.status === "connected" ? "#00FF9D" : "#FF3333"}
                                    strokeWidth="1"
                                    opacity="0.6"
                                >
                                    <animate
                                        attributeName="r"
                                        values="35;40;35"
                                        dur="1.5s"
                                        repeatCount="indefinite"
                                    />
                                    <animate
                                        attributeName="opacity"
                                        values="0.6;0.2;0.6"
                                        dur="1.5s"
                                        repeatCount="indefinite"
                                    />
                                </circle>
                            )}
                            
                            {pulseEffect && (
                                <circle
                                    cx="0"
                                    cy="0"
                                    r="30"
                                    fill="transparent"
                                    stroke="white"
                                    strokeWidth="2"
                                    opacity="0.8"
                                >
                                    <animate
                                        attributeName="r"
                                        values="30;50;30"
                                        dur="0.8s"
                                        repeatCount="1"
                                    />
                                    <animate
                                        attributeName="opacity"
                                        values="0.8;0;0.8"
                                        dur="0.8s"
                                        repeatCount="1"
                                    />
                                </circle>
                            )}
                            
                            <Machine
                                machine={machine}
                                x={0}
                                y={0}
                                onClick={() => onMachineClick(machine)}
                            />
                        </g>
                    );
                })}
                
                {highlightedMachine && positions[highlightedMachine] && (
                    <filter id="glow">
                        <feGaussianBlur stdDeviation="3.5" result="blur" />
                        <feComposite in="SourceGraphic" in2="blur" operator="over" />
                    </filter>
                )}
            </svg>
            
            <div className="visualizer-controls">
                <button 
                    onClick={handleZoomIn}
                    className="zoom-button"
                    style={{ transform: animationInProgress ? 'scale(1.1)' : 'scale(1)' }}
                >
                    +
                </button>
                <button 
                    onClick={handleZoomOut}
                    className="zoom-button"
                    style={{ transform: animationInProgress ? 'scale(0.9)' : 'scale(1)' }}
                >
                    -
                </button>
                <button 
                    onClick={handleResetPositions}
                    className="zoom-button reset-button"
                    style={{ transform: animationInProgress ? 'scale(1.1)' : 'scale(1)' }}
                >
                    Reset
                </button>
            </div>
        </div>
    );
};

export default Visualizer;

// ui/src/app/components/visualizer/visualizer.component.ts
import { Component, Input, Output, EventEmitter, OnChanges, SimpleChanges, ViewChild, ElementRef, NO_ERRORS_SCHEMA, AfterViewInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Machine, Link, Position } from '../../models/types';

@Component({
  selector: 'app-visualizer',
  standalone: true,
  imports: [CommonModule],
  schemas: [NO_ERRORS_SCHEMA],
  templateUrl: './visualizer.component.html',
  styleUrls: ['./visualizer.component.scss']
})
export class VisualizerComponent implements OnChanges, AfterViewInit {
  @Input() machines: Machine[] = [];
  @Input() links: Link[] = [];
  @Input() isReduced: boolean = false;
  @Input() initialPositions?: Record<string, Position>;
  @Output() machineClick = new EventEmitter<Machine>();
  @Output() positionsChange = new EventEmitter<Record<string, Position>>();

  @ViewChild('svgElement', { static: false }) svgRef!: ElementRef<SVGSVGElement>;
  Object = Object;

  positions: Record<string, Position> = {};
  dragging: string | null = null;
  viewBox = { x: 0, y: 0, width: 550, height: 350 };
  isPanning = false;
  lastPosition = { x: 0, y: 0 };
  scale = 1;

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['initialPositions']) {
      this.initializePositions();
    }
  }

  ngAfterViewInit(): void {
    if (this.machines.length > 0 && Object.keys(this.positions).length === 0) {
      this.initializePositions();
    }
  }

  initializePositions(): void {
    if (this.initialPositions && Object.keys(this.initialPositions).length > 0) {
      this.positions = { ...this.initialPositions };
    } else {
      const circlePositions = this.calculateCirclePositions();
      this.positions = { ...circlePositions };
    }

    const circlePositions = this.calculateCirclePositions();
    this.machines.forEach(machine => {
      if (!this.positions[machine.id]) {
        this.positions[machine.id] = circlePositions[machine.id];
      }
    });
  }

  calculateCirclePositions(): Record<string, Position> {
    const centerX = 275;
    const centerY = 175;
    const radius = 100;
    
    const circlePositions: Record<string, Position> = {};
    this.machines.forEach((machine, index) => {
      const angle = (index * 2 * Math.PI) / this.machines.length;
      circlePositions[machine.id] = {
        x: centerX + radius * Math.cos(angle),
        y: centerY + radius * Math.sin(angle)
      };
    });
    
    return circlePositions;
  }

  handleSvgMouseDown(event: MouseEvent): void {
    if (event.button === 0 && !this.dragging) {
      this.isPanning = true;
      this.lastPosition = { x: event.clientX, y: event.clientY };
    }
  }

  handleSvgMouseMove(event: MouseEvent): void {
    if (this.dragging) {
      const svg = this.svgRef.nativeElement;
      if (!svg) return;
      
      const point = svg.createSVGPoint();
      point.x = event.clientX;
      point.y = event.clientY;
      
      const ctm = svg.getScreenCTM();
      if (!ctm) return;
      
      const svgP = point.matrixTransform(ctm.inverse());
      
      this.positions = {
        ...this.positions,
        [this.dragging]: {
          x: svgP.x,
          y: svgP.y
        }
      };
      
      this.positionsChange.emit(this.positions);
    } else if (this.isPanning) {
      const dx = event.clientX - this.lastPosition.x;
      const dy = event.clientY - this.lastPosition.y;
      
      const panSpeed = 1 / this.scale;
      
      this.viewBox = {
        ...this.viewBox,
        x: this.viewBox.x - dx * panSpeed,
        y: this.viewBox.y - dy * panSpeed
      };
      
      this.lastPosition = { x: event.clientX, y: event.clientY };
    }
  }

  handleSvgMouseUp(): void {
    this.isPanning = false;
    this.dragging = null;
  }

  handleSvgMouseLeave(): void {
    this.isPanning = false;
    this.dragging = null;
  }

  handleMachineDragStart(id: string, event: MouseEvent): void {
    event.stopPropagation();
    this.dragging = id;
  }

  handleWheel(event: WheelEvent): void {
    event.preventDefault();
    
    const svg = this.svgRef.nativeElement;
    if (!svg) return;
    
    const point = svg.createSVGPoint();
    point.x = event.clientX;
    point.y = event.clientY;
    
    const ctm = svg.getScreenCTM();
    if (!ctm) return;
    
    const svgP = point.matrixTransform(ctm.inverse());
    
    const zoomFactor = event.deltaY > 0 ? 1.1 : 0.9;
    const newScale = Math.max(0.5, Math.min(5, this.scale * zoomFactor));
    
    const newWidth = this.viewBox.width * (this.scale / newScale);
    const newHeight = this.viewBox.height * (this.scale / newScale);
    
    const mouseXRatio = (svgP.x - this.viewBox.x) / this.viewBox.width;
    const mouseYRatio = (svgP.y - this.viewBox.y) / this.viewBox.height;
    
    const newX = svgP.x - mouseXRatio * newWidth;
    const newY = svgP.y - mouseYRatio * newHeight;
    
    this.viewBox = {
      x: newX,
      y: newY,
      width: newWidth,
      height: newHeight
    };
    
    this.scale = newScale;
  }

  handleZoomIn(): void {
    const newScale = Math.min(5, this.scale * 1.2);
    const centerX = this.viewBox.x + this.viewBox.width / 2;
    const centerY = this.viewBox.y + this.viewBox.height / 2;
    const newWidth = this.viewBox.width * (this.scale / newScale);
    const newHeight = this.viewBox.height * (this.scale / newScale);
    
    this.viewBox = {
      x: centerX - newWidth / 2,
      y: centerY - newHeight / 2,
      width: newWidth,
      height: newHeight
    };
    
    this.scale = newScale;
  }

  handleZoomOut(): void {
    const newScale = Math.max(0.5, this.scale / 1.2);
    const centerX = this.viewBox.x + this.viewBox.width / 2;
    const centerY = this.viewBox.y + this.viewBox.height / 2;
    const newWidth = this.viewBox.width * (this.scale / newScale);
    const newHeight = this.viewBox.height * (this.scale / newScale);
    
    this.viewBox = {
      x: centerX - newWidth / 2,
      y: centerY - newHeight / 2,
      width: newWidth,
      height: newHeight
    };
    
    this.scale = newScale;
  }

  getLinkStartX(link: Link): number {
    const angle = Math.atan2(
      this.positions[link.target].y - this.positions[link.source].y,
      this.positions[link.target].x - this.positions[link.source].x
    );
    return this.positions[link.source].x + Math.cos(angle) * 30;
  }

  getLinkStartY(link: Link): number {
    const angle = Math.atan2(
      this.positions[link.target].y - this.positions[link.source].y,
      this.positions[link.target].x - this.positions[link.source].x
    );
    return this.positions[link.source].y + Math.sin(angle) * 30;
  }

  getLinkEndX(link: Link): number {
    const angle = Math.atan2(
      this.positions[link.target].y - this.positions[link.source].y,
      this.positions[link.target].x - this.positions[link.source].x
    );
    return this.positions[link.target].x - Math.cos(angle) * 30;
  }

  getLinkEndY(link: Link): number {
    const angle = Math.atan2(
      this.positions[link.target].y - this.positions[link.source].y,
      this.positions[link.target].x - this.positions[link.source].x
    );
    return this.positions[link.target].y - Math.sin(angle) * 30;
  }

  getLinkColor(link: Link): string {
    const sourceMachine = this.machines.find(m => m.id === link.source);
    const targetMachine = this.machines.find(m => m.id === link.target);
    
    if (sourceMachine?.status === 'isolated' || targetMachine?.status === 'isolated') {
      return '#FF3333';
    }
    
    return '#00FF9D';
  }

  getLinkDashArray(link: Link): string {
    const sourceMachine = this.machines.find(m => m.id === link.source);
    const targetMachine = this.machines.find(m => m.id === link.target);
    
    if (sourceMachine?.status === 'isolated' || targetMachine?.status === 'isolated') {
      return '5,5';
    }
    
    return 'none';
  }

  handleResetPositions(): void {
    const freshCirclePositions = this.calculateCirclePositions();
    this.positions = freshCirclePositions;
    this.positionsChange.emit(freshCirclePositions);
    
    this.viewBox = { x: 0, y: 0, width: 550, height: 350 };
    this.scale = 1;
  }

  getViewBoxString(): string {
    return `${this.viewBox.x} ${this.viewBox.y} ${this.viewBox.width} ${this.viewBox.height}`;
  }

  onMachineClick(machine: Machine): void {
    this.machineClick.emit(machine);
  }

  trackByMachineId(index: number, machine: Machine): string {
    return machine.id;
  }

  trackByLinkIndex(index: number): number {
    return index;
  }
}
