// ui/src/app/components/machine/machine.component.ts
import { Component, Input, Output, EventEmitter, OnChanges, SimpleChanges, NO_ERRORS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Machine as MachineType } from '../../models/types';

@Component({
  selector: 'app-machine',
  standalone: true,
  imports: [CommonModule],
  schemas: [NO_ERRORS_SCHEMA], 
  templateUrl: './machine.component.html',
  styleUrls: ['./machine.component.scss']
})
export class MachineComponent implements OnChanges {
  @Input() machine!: MachineType;
  @Input() x: number = 0;
  @Input() y: number = 0;
  @Output() machineClick = new EventEmitter<void>();

  previousStatus: string = '';
  isTransitioning: boolean = false;
  circleClass: string = '';
  textClass: string = '';

  private transitionTimer?: number;

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['machine']) {
      this.updateClasses();
      
      if (this.previousStatus && this.previousStatus !== this.machine.status) {
        this.isTransitioning = true;
        
        if (this.transitionTimer) {
          clearTimeout(this.transitionTimer);
        }
        
        this.transitionTimer = window.setTimeout(() => {
          this.isTransitioning = false;
          this.previousStatus = this.machine.status;
        }, 1000);
      } else if (!this.previousStatus) {
        this.previousStatus = this.machine.status;
      }
    }
  }

  updateClasses(): void {
    this.circleClass = this.machine.status === 'connected' 
      ? 'machine-circle-connected' 
      : 'machine-circle-isolated';
    this.textClass = this.machine.status === 'connected' 
      ? 'machine-text-connected' 
      : 'machine-text-isolated';
  }

  handleClick(event: MouseEvent): void {
    const target = event.currentTarget as HTMLElement;
    if (target.classList.contains('dragging')) {
      target.classList.remove('dragging');
      return;
    }
    this.machineClick.emit();
  }

  getAnimationStyle(): string {
    if (this.isTransitioning) {
      return this.machine.status === 'connected'
        ? 'pulse-connected 0.5s ease 3'
        : 'pulse-isolated 0.5s ease 3';
    }
    return '';
  }

  ngOnDestroy(): void {
    if (this.transitionTimer) {
      clearTimeout(this.transitionTimer);
    }
  }
}
<g 
  (click)="handleClick($event)"
  [attr.transform]="'translate(' + x + ', ' + y + ')'"
  style="cursor: pointer;">
  
  <circle 
    [attr.class]="'machine-circle ' + circleClass"
    cx="0" 
    cy="0" 
    r="30"
    [style.animation]="getAnimationStyle()" />
  
  <text 
    [attr.class]="'machine-text ' + textClass"
    x="0" 
    y="0" 
    text-anchor="middle" 
    dominant-baseline="central">
    {{ machine.name }}
  </text>
</g>

// src/components/Machine.tsx
import React from 'react';
import { Machine as MachineType } from '../types';
import './Machine.css';

interface MachineProps {
    machine: MachineType;
    x: number;
    y: number;
    onClick: () => void;
}

const Machine: React.FC<MachineProps> = ({ machine, x, y, onClick }) => {
    const circleClass = machine.status === "connected" ? "machine-circle-connected" : "machine-circle-isolated";
    const textClass = machine.status === "connected" ? "machine-text-connected" : "machine-text-isolated";

    const handleClick = (e: React.MouseEvent) => {
        if (e.currentTarget.classList.contains('dragging')) {
            e.currentTarget.classList.remove('dragging');
            return;
        }
        onClick();
    };

    return (
        <g 
            className="machine" 
            onClick={handleClick} 
            transform={`translate(${x}, ${y})`}
            style={{ cursor: 'pointer' }}
        >
            <circle className={`machine-circle ${circleClass}`} cx="0" cy="0" r="30" />
            <text className={`machine-text ${textClass}`} x="0" y="0" textAnchor="middle" dominantBaseline="central">
                {machine.name}
            </text>
        </g>
    );
};

export default Machine;
