// ui/src/app/components/visualizer/visualizer.component.ts
import { Component, Input, Output, EventEmitter, OnChanges, SimpleChanges, ViewChild, ElementRef, NO_ERRORS_SCHEMA, AfterViewInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Machine, Link, Position } from '../../models/types';

@Component({
  selector: 'app-visualizer',
  standalone: true,
  imports: [CommonModule],
  schemas: [NO_ERRORS_SCHEMA],
  templateUrl: './visualizer.component.html',
  styleUrls: ['./visualizer.component.scss']
})
export class VisualizerComponent implements OnChanges, AfterViewInit {
  @Input() machines: Machine[] = [];
  @Input() links: Link[] = [];
  @Input() isReduced: boolean = false;
  @Input() initialPositions?: Record<string, Position>;
  @Output() machineClick = new EventEmitter<Machine>();
  @Output() positionsChange = new EventEmitter<Record<string, Position>>();

  @ViewChild('svgElement', { static: false }) svgRef!: ElementRef<SVGSVGElement>;
  Object = Object;

  positions: Record<string, Position> = {};
  dragging: string | null = null;
  viewBox = { x: 0, y: 0, width: 550, height: 350 };
  isPanning = false;
  lastPosition = { x: 0, y: 0 };
  scale = 1;

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['initialPositions']) {
      this.initializePositions();
    }
  }

  ngAfterViewInit(): void {
    if (this.machines.length > 0 && Object.keys(this.positions).length === 0) {
      this.initializePositions();
    }
  }

  initializePositions(): void {
    if (this.initialPositions && Object.keys(this.initialPositions).length > 0) {
      this.positions = { ...this.initialPositions };
    } else {
      const circlePositions = this.calculateCirclePositions();
      this.positions = { ...circlePositions };
    }

    const circlePositions = this.calculateCirclePositions();
    this.machines.forEach(machine => {
      if (!this.positions[machine.id]) {
        this.positions[machine.id] = circlePositions[machine.id];
      }
    });
  }

  calculateCirclePositions(): Record<string, Position> {
    const centerX = 275;
    const centerY = 175;
    const radius = 100;
    
    const circlePositions: Record<string, Position> = {};
    this.machines.forEach((machine, index) => {
      const angle = (index * 2 * Math.PI) / this.machines.length;
      circlePositions[machine.id] = {
        x: centerX + radius * Math.cos(angle),
        y: centerY + radius * Math.sin(angle)
      };
    });
    
    return circlePositions;
  }

  handleSvgMouseDown(event: MouseEvent): void {
    if (event.button === 0 && !this.dragging) {
      this.isPanning = true;
      this.lastPosition = { x: event.clientX, y: event.clientY };
    }
  }

  handleSvgMouseMove(event: MouseEvent): void {
    if (this.dragging) {
      const svg = this.svgRef.nativeElement;
      if (!svg) return;
      
      const point = svg.createSVGPoint();
      point.x = event.clientX;
      point.y = event.clientY;
      
      const ctm = svg.getScreenCTM();
      if (!ctm) return;
      
      const svgP = point.matrixTransform(ctm.inverse());
      
      this.positions = {
        ...this.positions,
        [this.dragging]: {
          x: svgP.x,
          y: svgP.y
        }
      };
      
      this.positionsChange.emit(this.positions);
    } else if (this.isPanning) {
      const dx = event.clientX - this.lastPosition.x;
      const dy = event.clientY - this.lastPosition.y;
      
      const panSpeed = 1 / this.scale;
      
      this.viewBox = {
        ...this.viewBox,
        x: this.viewBox.x - dx * panSpeed,
        y: this.viewBox.y - dy * panSpeed
      };
      
      this.lastPosition = { x: event.clientX, y: event.clientY };
    }
  }

  handleSvgMouseUp(): void {
    this.isPanning = false;
    this.dragging = null;
  }

  handleSvgMouseLeave(): void {
    this.isPanning = false;
    this.dragging = null;
  }

  handleMachineDragStart(id: string, event: MouseEvent): void {
    event.stopPropagation();
    this.dragging = id;
  }

  handleWheel(event: WheelEvent): void {
    event.preventDefault();
    
    const svg = this.svgRef.nativeElement;
    if (!svg) return;
    
    const point = svg.createSVGPoint();
    point.x = event.clientX;
    point.y = event.clientY;
    
    const ctm = svg.getScreenCTM();
    if (!ctm) return;
    
    const svgP = point.matrixTransform(ctm.inverse());
    
    const zoomFactor = event.deltaY > 0 ? 1.1 : 0.9;
    const newScale = Math.max(0.5, Math.min(5, this.scale * zoomFactor));
    
    const newWidth = this.viewBox.width * (this.scale / newScale);
    const newHeight = this.viewBox.height * (this.scale / newScale);
    
    const mouseXRatio = (svgP.x - this.viewBox.x) / this.viewBox.width;
    const mouseYRatio = (svgP.y - this.viewBox.y) / this.viewBox.height;
    
    const newX = svgP.x - mouseXRatio * newWidth;
    const newY = svgP.y - mouseYRatio * newHeight;
    
    this.viewBox = {
      x: newX,
      y: newY,
      width: newWidth,
      height: newHeight
    };
    
    this.scale = newScale;
  }

  handleZoomIn(): void {
    const newScale = Math.min(5, this.scale * 1.2);
    const centerX = this.viewBox.x + this.viewBox.width / 2;
    const centerY = this.viewBox.y + this.viewBox.height / 2;
    const newWidth = this.viewBox.width * (this.scale / newScale);
    const newHeight = this.viewBox.height * (this.scale / newScale);
    
    this.viewBox = {
      x: centerX - newWidth / 2,
      y: centerY - newHeight / 2,
      width: newWidth,
      height: newHeight
    };
    
    this.scale = newScale;
  }

  handleZoomOut(): void {
    const newScale = Math.max(0.5, this.scale / 1.2);
    const centerX = this.viewBox.x + this.viewBox.width / 2;
    const centerY = this.viewBox.y + this.viewBox.height / 2;
    const newWidth = this.viewBox.width * (this.scale / newScale);
    const newHeight = this.viewBox.height * (this.scale / newScale);
    
    this.viewBox = {
      x: centerX - newWidth / 2,
      y: centerY - newHeight / 2,
      width: newWidth,
      height: newHeight
    };
    
    this.scale = newScale;
  }

  getLinkStartX(link: Link): number {
    const angle = Math.atan2(
      this.positions[link.target].y - this.positions[link.source].y,
      this.positions[link.target].x - this.positions[link.source].x
    );
    return this.positions[link.source].x + Math.cos(angle) * 30;
  }

  getLinkStartY(link: Link): number {
    const angle = Math.atan2(
      this.positions[link.target].y - this.positions[link.source].y,
      this.positions[link.target].x - this.positions[link.source].x
    );
    return this.positions[link.source].y + Math.sin(angle) * 30;
  }

  getLinkEndX(link: Link): number {
    const angle = Math.atan2(
      this.positions[link.target].y - this.positions[link.source].y,
      this.positions[link.target].x - this.positions[link.source].x
    );
    return this.positions[link.target].x - Math.cos(angle) * 30;
  }

  getLinkEndY(link: Link): number {
    const angle = Math.atan2(
      this.positions[link.target].y - this.positions[link.source].y,
      this.positions[link.target].x - this.positions[link.source].x
    );
    return this.positions[link.target].y - Math.sin(angle) * 30;
  }

  getLinkColor(link: Link): string {
    const sourceMachine = this.machines.find(m => m.id === link.source);
    const targetMachine = this.machines.find(m => m.id === link.target);
    
    if (sourceMachine?.status === 'isolated' || targetMachine?.status === 'isolated') {
      return '#FF3333';
    }
    
    return '#00FF9D';
  }

  getLinkDashArray(link: Link): string {
    const sourceMachine = this.machines.find(m => m.id === link.source);
    const targetMachine = this.machines.find(m => m.id === link.target);
    
    if (sourceMachine?.status === 'isolated' || targetMachine?.status === 'isolated') {
      return '5,5';
    }
    
    return 'none';
  }

  handleResetPositions(): void {
    const freshCirclePositions = this.calculateCirclePositions();
    this.positions = freshCirclePositions;
    this.positionsChange.emit(freshCirclePositions);
    
    this.viewBox = { x: 0, y: 0, width: 550, height: 350 };
    this.scale = 1;
  }

  getViewBoxString(): string {
    return `${this.viewBox.x} ${this.viewBox.y} ${this.viewBox.width} ${this.viewBox.height}`;
  }

  onMachineClick(machine: Machine): void {
    this.machineClick.emit(machine);
  }

  trackByMachineId(index: number, machine: Machine): string {
    return machine.id;
  }

  trackByLinkIndex(index: number): number {
    return index;
  }
}

// src/components/Visualizer.tsx
import React, { useState, useRef, useEffect, useCallback } from 'react';
import Machine from './Machine';
import MachineLink from './MachineLink';
import { Machine as MachineType, Link } from '../types';
import './Visualizer.css';

interface VisualizerProps {
    machines: MachineType[];
    links: Link[];
    onMachineClick: (machine: MachineType) => void;
    isReduced: boolean;
    initialPositions?: Record<string, Position>;
    onPositionsChange?: (positions: Record<string, Position>) => void;
}

interface Position {
    x: number;
    y: number;
}

const Visualizer: React.FC<VisualizerProps> = ({ 
    machines, 
    links, 
    onMachineClick,
    isReduced,
    initialPositions,
    onPositionsChange
}) => {
    const svgRef = useRef<SVGSVGElement>(null);
    const [positions, setPositions] = useState<Record<string, Position>>({});
    const [dragging, setDragging] = useState<string | null>(null);
    const [viewBox, setViewBox] = useState({ x: 0, y: 0, width: 550, height: 350 });
    const [isPanning, setIsPanning] = useState(false);
    const [lastPosition, setLastPosition] = useState({ x: 0, y: 0 });
    const [scale, setScale] = useState(1);
    
    // Calculate initial positions in a circle - memoized with useCallback
    const calculateCirclePositions = useCallback(() => {
        const centerX = 275;
        const centerY = 175;
        const radius = 100;
        
        const circlePositions: Record<string, Position> = {};
        machines.forEach((machine, index) => {
            const angle = (index * 2 * Math.PI) / machines.length;
            circlePositions[machine.id] = {
                x: centerX + radius * Math.cos(angle),
                y: centerY + radius * Math.sin(angle)
            };
        });
        
        return circlePositions;
    }, [machines]);
    
    // Initialize machine positions
    useEffect(() => {
        // Use initial positions if provided, otherwise calculate circle positions
        if (initialPositions && Object.keys(initialPositions).length > 0) {
            setPositions(initialPositions);
        } else {
            const freshCirclePositions = calculateCirclePositions();
            setPositions(freshCirclePositions);
        }
    }, [initialPositions, calculateCirclePositions]);
    
    // Update positions when new machines are added
    useEffect(() => {
        const freshCirclePositions = calculateCirclePositions();
        
        // Only set positions for machines that don't have them yet
        setPositions(prev => {
            const updatedPositions = { ...prev };
            machines.forEach(machine => {
                if (!updatedPositions[machine.id]) {
                    updatedPositions[machine.id] = freshCirclePositions[machine.id];
                }
            });
            
            return updatedPositions;
        });
    }, [machines, calculateCirclePositions]);
    
    // Handle mouse down on SVG for panning
    const handleSvgMouseDown = (e: React.MouseEvent) => {
        if (e.button === 0 && !dragging) { // Left click and not dragging a machine
            setIsPanning(true);
            setLastPosition({ x: e.clientX, y: e.clientY });
        }
    };
    
    // Handle mouse move for panning and dragging
    const handleSvgMouseMove = (e: React.MouseEvent) => {
        if (dragging) {
            // We're dragging a machine
            const svg = svgRef.current;
            if (!svg) return;
            
            const point = svg.createSVGPoint();
            point.x = e.clientX;
            point.y = e.clientY;
            
            // Convert client coordinates to SVG coordinates
            const svgP = point.matrixTransform(svg.getScreenCTM()?.inverse());
            
            const newPositions = {
                ...positions,
                [dragging]: {
                    x: svgP.x,
                    y: svgP.y
                }
            };
            
            setPositions(newPositions);
            
            // Call the callback if provided
            if (onPositionsChange) {
                onPositionsChange(newPositions);
            }
        } else if (isPanning) {
            // We're panning the view
            const dx = e.clientX - lastPosition.x;
            const dy = e.clientY - lastPosition.y;
            
            // Adjust based on current scale
            const panSpeed = 1 / scale;
            
            setViewBox(prev => ({
                ...prev,
                x: prev.x - dx * panSpeed,
                y: prev.y - dy * panSpeed
            }));
            
            setLastPosition({ x: e.clientX, y: e.clientY });
        }
    };
    
    // Handle mouse up for ending panning and dragging
    const handleSvgMouseUp = () => {
        setIsPanning(false);
        setDragging(null);
    };
    
    // Handle mouse leave for ending panning and dragging
    const handleSvgMouseLeave = () => {
        setIsPanning(false);
        setDragging(null);
    };
    
    // Handle machine drag start
    const handleMachineDragStart = (id: string, e: React.MouseEvent) => {
        e.stopPropagation(); // Prevent SVG from starting a pan operation
        setDragging(id);
    };
    
    // Handle zoom with mouse wheel
    const handleWheel = (e: React.WheelEvent) => {
        e.preventDefault();
        
        const svg = svgRef.current;
        if (!svg) return;
        
        // Get mouse position in SVG coordinates
        const point = svg.createSVGPoint();
        point.x = e.clientX;
        point.y = e.clientY;
        const svgP = point.matrixTransform(svg.getScreenCTM()?.inverse());
        
        // Calculate new scale
        const zoomFactor = e.deltaY > 0 ? 1.1 : 0.9;
        const newScale = Math.max(0.5, Math.min(5, scale * zoomFactor));
        
        // Calculate new viewBox dimensions
        const newWidth = viewBox.width * (scale / newScale);
        const newHeight = viewBox.height * (scale / newScale);
        
        // Calculate new viewBox position to zoom toward/away from mouse
        const mouseXRatio = (svgP.x - viewBox.x) / viewBox.width;
        const mouseYRatio = (svgP.y - viewBox.y) / viewBox.height;
        
        const newX = svgP.x - mouseXRatio * newWidth;
        const newY = svgP.y - mouseYRatio * newHeight;
        
        setViewBox({
            x: newX,
            y: newY,
            width: newWidth,
            height: newHeight
        });
        
        setScale(newScale);
    };
    
    // Handle zoom in button
    const handleZoomIn = () => {
        setScale(prev => {
            const newScale = Math.min(5, prev * 1.2);
            // Adjust viewBox to maintain center
            setViewBox(prev => {
                const centerX = prev.x + prev.width / 2;
                const centerY = prev.y + prev.height / 2;
                const newWidth = prev.width * (scale / newScale);
                const newHeight = prev.height * (scale / newScale);
                return {
                    x: centerX - newWidth / 2,
                    y: centerY - newHeight / 2,
                    width: newWidth,
                    height: newHeight
                };
            });
            return newScale;
        });
    };
    
    // Handle zoom out button
    const handleZoomOut = () => {
        setScale(prev => {
            const newScale = Math.max(0.5, prev / 1.2);
            // Adjust viewBox to maintain center
            setViewBox(prev => {
                const centerX = prev.x + prev.width / 2;
                const centerY = prev.y + prev.height / 2;
                const newWidth = prev.width * (scale / newScale);
                const newHeight = prev.height * (scale / newScale);
                return {
                    x: centerX - newWidth / 2,
                    y: centerY - newHeight / 2,
                    width: newWidth,
                    height: newHeight
                };
            });
            return newScale;
        });
    };
    
    // Handle reset button
    const handleResetPositions = () => {
        // Calculate fresh circle positions to ensure consistency
        const freshCirclePositions = calculateCirclePositions();
        setPositions(freshCirclePositions);
        
        // Also update in localStorage via the callback
        if (onPositionsChange) {
            onPositionsChange(freshCirclePositions);
        }
        
        // Reset viewBox and scale
        setViewBox({ x: 0, y: 0, width: 550, height: 350 });
        setScale(1);
    };
    
    // Compute viewBox string
    const viewBoxString = `${viewBox.x} ${viewBox.y} ${viewBox.width} ${viewBox.height}`;
    
    return (
        <div className={`visualizer ${isReduced ? 'reduced' : ''}`}>
            <svg 
                ref={svgRef}
                width="100%" 
                height="100%" 
                viewBox={viewBoxString}
                onMouseDown={handleSvgMouseDown}
                onMouseMove={handleSvgMouseMove}
                onMouseUp={handleSvgMouseUp}
                onMouseLeave={handleSvgMouseLeave}
                onWheel={handleWheel}
            >
                {links.map((link, index) => {
                    // Only render links if we have positions for both machines
                    if (!positions[link.source] || !positions[link.target]) return null;
                    
                    return (
                        <MachineLink
                            key={index}
                            sourceX={positions[link.source].x}
                            sourceY={positions[link.source].y}
                            targetX={positions[link.target].x}
                            targetY={positions[link.target].y}
                            type={link.type}
                        />
                    );
                })}
                
                {machines.map(machine => {
                    // Only render machines if we have positions for them
                    if (!positions[machine.id]) return null;
                    
                    return (
                        <g 
                            key={machine.id}
                            onMouseDown={(e) => handleMachineDragStart(machine.id, e)}
                        >
                            <Machine
                                machine={machine}
                                x={positions[machine.id].x}
                                y={positions[machine.id].y}
                                onClick={() => onMachineClick(machine)}
                            />
                        </g>
                    );
                })}
            </svg>
            
            {/* Zoom controls - positioned in bottom right */}
            <div className="visualizer-controls">
                <button 
                    onClick={handleZoomIn}
                    className="zoom-button"
                >
                    +
                </button>
                <button 
                    onClick={handleZoomOut}
                    className="zoom-button"
                >
                    -
                </button>
                <button 
                    onClick={handleResetPositions}
                    className="zoom-button"
                >
                    Reset
                </button>
            </div>
        </div>
    );
};

export default Visualizer;
