// ui/src/App.tsx
import React, { useState, useRef, useEffect, useCallback } from 'react';
import Header from './components/Header';
import Visualizer from './components/Visualizer';
import Information from './components/Information';
import Footer from './components/Footer';
import { Machine, Link } from './types';
import './App.css';

interface Position {
  x: number;
  y: number;
}

const App: React.FC = () => {
  const [selectedMachine, setSelectedMachine] = useState<Machine | null>(null);
  const [machinePositions, setMachinePositions] = useState<Record<string, Position>>({});
  const [machines, setMachines] = useState<Machine[]>([]);
  const [previousMachines, setPreviousMachines] = useState<Machine[]>([]);
  const [links, setLinks] = useState<Link[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [statusChanges, setStatusChanges] = useState<Record<string, boolean>>({});
  const visualizerRef = useRef<HTMLDivElement>(null);
  
  const generateLinks = (machinesList: Machine[]): Link[] => {
    const generatedLinks: Link[] = [];
    
    for (let i = 0; i < machinesList.length; i++) {
      for (let j = i + 1; j < machinesList.length; j++) {
        if (machinesList[i].status === "connected" && machinesList[j].status === "connected") {
          generatedLinks.push({ 
            source: machinesList[i].id, 
            target: machinesList[j].id,
            type: "connected"
          });
        } else {
          generatedLinks.push({ 
            source: machinesList[i].id, 
            target: machinesList[j].id,
            type: "isolated"
          });
        }
      }
    }
    
    return generatedLinks;
  };
  
  // Détection des changements d'état des machines
  useEffect(() => {
    const changes: Record<string, boolean> = {};
    
    machines.forEach(machine => {
      const previousMachine = previousMachines.find(m => m.id === machine.id);
      if (previousMachine && previousMachine.status !== machine.status) {
        changes[machine.id] = true;
      }
    });
    
    if (Object.keys(changes).length > 0) {
      setStatusChanges(changes);
      
      // Réinitialiser après un délai
      const timer = setTimeout(() => {
        setStatusChanges({});
      }, 1500);
      
      return () => clearTimeout(timer);
    }
  }, [machines, previousMachines]);
  
  const fetchMachines = useCallback(async () => {
    try {
      setIsLoading(true);
      const response = await fetch('/api/machines');
      
      if (!response.ok) {
        throw new Error(`Failed to fetch machines: ${response.status}`);
      }
      
      const data = await response.json();
      
      // Sauvegarder l'état précédent pour détecter les changements
      setPreviousMachines(machines);
      setMachines(data);
      
      const newLinks = generateLinks(data);
      setLinks(newLinks);
      
      if (selectedMachine) {
        const updatedSelectedMachine = data.find(m => m.id === selectedMachine.id) || null;
        setSelectedMachine(updatedSelectedMachine);
      }
      
      setIsLoading(false);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An unknown error occurred');
      setIsLoading(false);
      
      if (machines.length === 0) {
        const sampleMachines = [
          { "id": "1", "name": "1", "ip": "xxx.xxx.xxx.xxx", "mac": "xx:xx:xx:xx:xx:xx", "lastUpdate": "01/03/2025", "status": "connected" },
          { "id": "2", "name": "2", "ip": "xxx.xxx.xxx.xxx", "mac": "xx:xx:xx:xx:xx:xx", "lastUpdate": "28/02/2025", "status": "isolated" },
          { "id": "3", "name": "3", "ip": "xxx.xxx.xxx.xxx", "mac": "xx:xx:xx:xx:xx:xx", "lastUpdate": "02/03/2025", "status": "connected" },
          { "id": "4", "name": "4", "ip": "xxx.xxx.xxx.xxx", "mac": "xx:xx:xx:xx:xx:xx", "lastUpdate": "03/03/2025", "status": "connected" },
        ];
        
        setMachines(sampleMachines);
        setPreviousMachines(sampleMachines);
        setLinks(generateLinks(sampleMachines));
      }
    } finally {
      setIsLoading(false);
    }
  }, [selectedMachine, machines.length, machines]);
  
  // Initial fetch on component mount
  useEffect(() => {
    fetchMachines();
    
    // Load saved positions on initial render
    const savedPositions = localStorage.getItem('machinePositions');
    if (savedPositions) {
      try {
        setMachinePositions(JSON.parse(savedPositions));
      } catch (e) {
        console.error('Failed to load saved positions', e);
      }
    }
  }, [fetchMachines]);
  

  useEffect(() => {
    const interval = setInterval(() => {
      fetchMachines();
    }, 10000);
    
    return () => clearInterval(interval);
  }, [fetchMachines]);
  
  const handleMachineClick = (machine: Machine) => {
    if (selectedMachine && selectedMachine.id === machine.id) {
      setSelectedMachine(null);
    } else {
      setSelectedMachine(machine);
    }
  };
  
  const updateMachinePositions = (positions: Record<string, Position>) => {
    setMachinePositions(positions);
    
    localStorage.setItem('machinePositions', JSON.stringify(positions));
  };
  
  return (
    <div className="app">
      <Header />
      <div className="main-content">
        {selectedMachine && (
          <Information machine={selectedMachine} />
        )}
        <div 
          ref={visualizerRef} 
          style={{ flex: 1, height: '100%' }}
        >
          {isLoading && machines.length === 0 ? (
            <div className="loading-container">
              <div className="loading-spinner"></div>
              <p>Loading machines...</p>
            </div>
          ) : error && machines.length === 0 ? (
            <div className="error-container">
              <p>Error: {error}</p>
              <button onClick={fetchMachines}>Retry</button>
            </div>
          ) : (
            <Visualizer 
              machines={machines} 
              links={links} 
              onMachineClick={handleMachineClick}
              isReduced={selectedMachine !== null}
              initialPositions={machinePositions}
              onPositionsChange={updateMachinePositions}
              statusChanges={statusChanges}
            />
          )}
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default App;

// pocFront_Angular/src/app/app.component.ts
import { Component, OnInit, PLATFORM_ID, inject } from '@angular/core';
import { CommonModule, isPlatformBrowser } from '@angular/common';
import { HeaderComponent } from './components/header/header.component';
import { VisualizerComponent } from './components/visualizer/visualizer.component';
import { InformationComponent } from './components/information/information.component';
import { FooterComponent } from './components/footer/footer.component';
import { Machine, Link, Position } from './models/types';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    CommonModule,
    HeaderComponent,
    VisualizerComponent,
    InformationComponent,
    FooterComponent
  ],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {
  private platformId = inject(PLATFORM_ID);
  private isBrowser: boolean = isPlatformBrowser(this.platformId);

  machines: Machine[] = [
  {
    id: '1',
    name: '1',
    ip: '192.168.1.10',
    mac: '00:1B:44:11:3A:B7',
    lastUpdate: '01/03/2025',
    status: 'connected'
  },
  {
    id: '2',
    name: '2',
    ip: '192.168.1.20',
    mac: '00:1B:44:11:3A:B8',
    lastUpdate: '28/02/2025',
    status: 'isolated'
  },
  {
    id: '3',
    name: '3',
    ip: '192.168.1.30',
    mac: '00:1B:44:11:3A:B9',
    lastUpdate: '02/03/2025',
    status: 'connected'
  },
  {
    id: '4',
    name: '4',
    ip: '192.168.1.40',
    mac: '00:1B:44:11:3A:C0',
    lastUpdate: '03/03/2025',
    status: 'connected'
  }
];

  links: Link[] = [
    { source: '1', target: '2', type: 'connected' },
    { source: '2', target: '3', type: 'isolated' },
    { source: '3', target: '4', type: 'connected' },
    { source: '4', target: '1', type: 'connected' },
    { source: '1', target: '3', type: 'connected' },
    { source: '2', target: '4', type: 'isolated' }
  ];

  selectedMachine: Machine | null = null;
  positions: Record<string, Position> = {};

  ngOnInit(): void {
    if (this.isBrowser) {
      const savedPositions = localStorage.getItem('machinePositions');
      if (savedPositions) {
        try {
          this.positions = JSON.parse(savedPositions);
        } catch (e) {
          console.error('Error loading saved positions:', e);
        }
      }
    }
  }

  onMachineClick(machine: Machine): void {
    if (this.selectedMachine?.id === machine.id) {
      this.selectedMachine = null;
    } else {
      this.selectedMachine = machine;
    }
    console.log('Machine clicked:', machine);
  }

  onPositionsChange(positions: Record<string, Position>): void {
    this.positions = positions;
    if (this.isBrowser) {
      localStorage.setItem('machinePositions', JSON.stringify(positions));
    }
  }

  private simulateStatusChanges(): void {
    if (!this.isBrowser) return;

    setInterval(() => {
      const randomIndex = Math.floor(Math.random() * this.machines.length);
      const machine = this.machines[randomIndex];
      
      machine.status = machine.status === 'connected' ? 'isolated' : 'connected';
      
      const now = new Date();
      machine.lastUpdate = now.toISOString().replace('T', ' ').substring(0, 19);
      
      this.links = this.links.map(link => {
        if (link.source === machine.id || link.target === machine.id) {
          return {
            ...link,
            type: machine.status
          };
        }
        return link;
      });

      this.machines = [...this.machines];
      this.links = [...this.links];

      if (this.selectedMachine?.id === machine.id) {
        this.selectedMachine = { ...machine };
      }

      console.log(`Machine ${machine.name} changed to ${machine.status}`);
    }, 5000);
  }
}
<app-header></app-header>

<div class="main-content">
  <app-information 
    *ngIf="selectedMachine"
    [machine]="selectedMachine">
  </app-information>
  
  <app-visualizer
    [machines]="machines"
    [links]="links"
    [isReduced]="!!selectedMachine"
    [initialPositions]="positions"
    (machineClick)="onMachineClick($event)"
    (positionsChange)="onPositionsChange($event)">
  </app-visualizer>
</div>

<app-footer></app-footer>
