// src/components/Information.tsx
import React from 'react';
import { Machine } from '../types';
import './Information.css';

interface InformationProps {
    machine: Machine;
}

const Information: React.FC<InformationProps> = ({ machine }) => {
    const circleClass = machine.status === "connected" ? "machine-circle-small-connected" : "machine-circle-small-isolated";
    const textClass = machine.status === "connected" ? "machine-text-small-connected" : "machine-text-small-isolated";
    
    return (
        <div className="information" data-status={machine.status}>
            <div className="info-header">
                <svg width="60" height="60" viewBox="0 0 80 80">
                    <circle className={`machine-circle-small ${circleClass}`} cx="40" cy="40" r="30" />
                    <text className={`machine-text-small ${textClass}`} x="40" y="40" textAnchor="middle" dominantBaseline="central">
                        {machine.name}
                    </text>
                </svg>
            </div>
            <div className="info-item">
                <div className="info-label">ID :</div> 
                <div className="info-value">{machine.id.padStart(7, 'x')}</div>
            </div>
            <div className="info-item">
                <div className="info-label">IP :</div> 
                <div className="info-value">{machine.ip}</div>
            </div>
            {machine.mac && (
                <div className="info-item">
                    <div className="info-label">MAC :</div> 
                    <div className="info-value">{machine.mac}</div>
                </div>
            )}
            <div className="info-item">
                <div className="info-label">Last update :</div> 
                <div className="info-value">{machine.lastUpdate}</div>
            </div>
            <div className="info-item">
                <div className="info-label">Status :</div> 
                <div className={`info-value ${machine.status === "connected" ? "status-connected" : "status-isolated"}`}>
                    {machine.status}
                </div>
            </div>
        </div>
    );
};

export default Information;

// ui/src/app/components/information/information.component.ts
import { Component, Input, OnChanges, SimpleChanges, NO_ERRORS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Machine } from '../../models/types';

@Component({
  selector: 'app-information',
  standalone: true,
  imports: [CommonModule],
  schemas: [NO_ERRORS_SCHEMA],
  templateUrl: './information.component.html',
  styleUrls: ['./information.component.scss']
})
export class InformationComponent implements OnChanges {
  @Input() machine!: Machine;

  previousStatus: string = '';
  isTransitioning: boolean = false;
  circleClass: string = '';
  textClass: string = '';

  private transitionTimer?: number;

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['machine']) {
      this.updateClasses();
      
      if (this.previousStatus && this.previousStatus !== this.machine.status) {
        this.isTransitioning = true;
        
        if (this.transitionTimer) {
          clearTimeout(this.transitionTimer);
        }
        
        this.transitionTimer = window.setTimeout(() => {
          this.isTransitioning = false;
          this.previousStatus = this.machine.status;
        }, 1000);
      } else if (!this.previousStatus) {
        this.previousStatus = this.machine.status;
      }
    }
  }

  updateClasses(): void {
    this.circleClass = this.machine.status === 'connected'
      ? 'machine-circle-small-connected'
      : 'machine-circle-small-isolated';
    this.textClass = this.machine.status === 'connected'
      ? 'machine-text-small-connected'
      : 'machine-text-small-isolated';
  }

  getAnimationStyle(): string {
    if (this.isTransitioning) {
      return this.machine.status === 'connected'
        ? 'pulse-connected 0.5s ease 3'
        : 'pulse-isolated 0.5s ease 3';
    }
    return '';
  }

  getPaddedId(): string {
    return this.machine.id.padStart(7, 'x');
  }

  ngOnDestroy(): void {
    if (this.transitionTimer) {
      clearTimeout(this.transitionTimer);
    }
  }
}
<div 
    [attr.class]="'information' + (isTransitioning ? ' transitioning' : '')"
    [attr.data-status]="machine.status">
    
    <div class="info-header">
        <svg width="60" height="60" viewBox="0 0 80 80">
        <circle 
            [attr.class]="'machine-circle-small ' + circleClass"
            cx="40" 
            cy="40" 
            r="30"
            [style.animation]="getAnimationStyle()" />
        
        <text 
            [attr.class]="'machine-text-small ' + textClass"
            x="40" 
            y="40" 
            text-anchor="middle" 
            dominant-baseline="central">
            {{ machine.name }}
        </text>
        </svg>
    </div>
    
    <div class="info-item">
        <div class="info-label">ID :</div> 
        <div class="info-value">{{ getPaddedId() }}</div>
    </div>
    
    <div class="info-item">
        <div class="info-label">IP :</div> 
        <div class="info-value">{{ machine.ip }}</div>
    </div>
    
    <div class="info-item" *ngIf="machine.mac">
        <div class="info-label">MAC :</div> 
        <div class="info-value">{{ machine.mac }}</div>
    </div>
    
    <div class="info-item">
        <div class="info-label">Last update :</div> 
        <div class="info-value">{{ machine.lastUpdate }}</div>
    </div>
    
    <div class="info-item">
        <div class="info-label">Status :</div> 
        <div [attr.class]="'info-value ' + (machine.status === 'connected' ? 'status-connected' : 'status-isolated')">
        {{ machine.status }}
        </div>
    </div>
</div>
